# Generated by Django 5.2.4 on 2025-07-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
